LINKS = [
    "https://www.roseltorg.ru/knowledge_db/com/article/zapros-predlozheniy-po-223fz-procedura-i-sroki",
    "https://www.roseltorg.ru/knowledge_db/com/video/dogovor-v-korporativnykh-zakupkakh",
    "https://www.roseltorg.ru/knowledge_db/com/article/zakupki-malogo-obema-po-223fz-poryadok-i-trebovaniya",
    "https://www.roseltorg.ru/knowledge_db/com/notes/s-1-yanvarya-2026-goda-rasshiritsya-perechen-zakazchikov-chi-proekty-zakupok-po-223fz-budut",
    "https://www.roseltorg.ru/knowledge_db/com/article/223fz-prostymi-slovami-rukovodstvo-dlya-nachinayuschikh",
    "https://www.roseltorg.ru/knowledge_db/com/notes/novyy-interfeys-raboty-s-zaprosami-na-sekcii-korp",
    "https://www.roseltorg.ru/knowledge_db/com/notes/napravlenie-alternativnykh-predlozheniy-v-sekcii-roseltorgkorporativnye-zakupki",
    "https://www.roseltorg.ru/knowledge_db/com/video/obzor-pravoprimenitelnoy-praktiki-po-zakonu-no-223fz-v-pervom-polugodii-2025-goda",
    "https://www.roseltorg.ru/knowledge_db/services/article/bankovskaya-garantiya-po-223-fz",
    "https://www.roseltorg.ru/knowledge_db/services/article/bankovskaya-garantiya-dlya-zakrytykh-zakupok-v-ramkakh-44fz-i-223fz",
    "https://www.roseltorg.ru/knowledge_db/com/instr/gk-rosatom",
    "https://www.roseltorg.ru/knowledge_db/kim/article/inter_rao",
    "https://www.roseltorg.ru/knowledge_db/ecp-info/article/mchd-dlya-direktora",
    "https://www.roseltorg.ru/knowledge_db/ecp-info/article/vidy-mashinochitaemykh-doverennostey-mchd-dlya-onlaynkommunikaciy-s-gossistemami-v-2025-godu",
    "https://www.roseltorg.ru/knowledge_db/ecp-info/notes/s-1-avgusta-2025-g-mchd-formata-003-stanet-obyazatelnoy-dlya-predstavleniya-otchyotnosti-v-rosstat",
    "https://www.roseltorg.ru/knowledge_db/ecp-info/notes/fgis-lk-prinimaet-edinuyu-mchd-formata-003",
    "https://www.roseltorg.ru/knowledge_db/registration/instr/universalnaya-registraciya-postavschika-pokupatelya-na-ploschadke-roseltorg",
    "https://www.roseltorg.ru/knowledge_db/registration/instr/kak-postavschiku-pokupatelyu-registrirovatsya-vo-vsekh-13-torgovykh-sekciyakh-i-v-tryokh",
    "https://www.roseltorg.ru/knowledge_db/com/article/zapros-predlozheniy-po-223fz-procedura-i-sroki",
    "https://www.roseltorg.ru/knowledge_db/sales/article/kak-osporit-rezultaty-torgov-esli-byli-narusheniya",
    "https://www.roseltorg.ru/knowledge_db/sales/article/chto-znachit-imuschestvo-s-torgov-razbiraemsya-v-terminakh",
    "https://www.roseltorg.ru/knowledge_db/sales/article/sravnenie-cen-torgi-vs-vtorichnyy-rynok",
    "https://www.roseltorg.ru/knowledge_db/com/notes/s-1-yanvarya-2026-goda-rasshiritsya-perechen-zakazchikov-chi-proekty-zakupok-po-223fz-budut",
    "https://www.roseltorg.ru/knowledge_db/com/article/chto-takoe-kommercheskie-zakupki",
    "https://www.roseltorg.ru/knowledge_db/com/article/223fz-prostymi-slovami-rukovodstvo-dlya-nachinayuschikh",
    "https://www.roseltorg.ru/knowledge_db/com/notes/napravlenie-alternativnykh-predlozheniy-v-sekcii-roseltorgkorporativnye-zakupki",
    "https://www.roseltorg.ru/knowledge_db/com/video/obzor-pravoprimenitelnoy-praktiki-po-zakonu-no-223fz-v-pervom-polugodii-2025-goda",
    "https://www.roseltorg.ru/knowledge_db/com/article/postavsik/vkhod-i-vykhod",
    "https://www.roseltorg.ru/knowledge_db/com/article/5-priemov-kotorye-pomogut-optimizirovat-zakupki-v-vashey-organizacii",
]

HEADERS =  {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Connection': 'keep-alive',
    'Upgrade-Insecure-Requests': '1',
}